language: php
sudo: false
matrix:
  include:
  - php: 5.3
    dist: precise
  - php: 5.4
    dist: precise
  - php: 5.5
    dist: precise
  - php: 5.6
  - php: 7.0
  - php: hhvm
  fast_finish: true
script: ./test.sh
